resolver: lts-7.7

packages:
- '.'
- '../core'

extra-deps:
- ghcjs-dom-0.7.0.2
- ghcjs-dom-jsffi-0.7.0.2


compiler: ghcjs-0.2.1.9007007_ghc-8.0.1
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007007_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-11-03-lts-7.7-9007007.tar.gz
          sha1: ce169f85f1c49ad613ae77fc494d5565452ff59a
